CREATE TABLE "BOARD" (
	"COMMENT_NUM"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL,
	"BOARD_TITLE"	VARCHAR(200)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR(1000)		NULL,
	"BOARD_COUNT"	NUMBER		NOT NULL,
	"BOARD_DATE"	VARCHAR2(10)		NOT NULL
);

CREATE TABLE "MEMBER" (
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL,
	"MNAME"	VARCHAR2(50)		NOT NULL,
	"MBIRTHDAY"	VARCHAR2(10)		NULL,
	"GENDER"	VARCHAR2(10)		NOT NULL,
	"HEIGHT"	NUMBER		NULL,
	"WEIGHT"	NUMBER		NULL,
	"SESSIONKEY"	VARCHAR2(63)		NULL,
	"SESSIONLIMIT"	VARCHAR2(63)		NULL,
	"GOOGLEID"	VARCHAR2(63)		NULL,
	"NAVERID"	VARCHAR2(63)		NULL,
	"KAKAOID"	VARCHAR2(63)		NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '이메일 형식';

COMMENT ON COLUMN "MEMBER"."MNAME" IS '이름';

COMMENT ON COLUMN "MEMBER"."MBIRTHDAY" IS 'YYYYMMDD';

COMMENT ON COLUMN "MEMBER"."GENDER" IS 'MAN, WOMAN';

COMMENT ON COLUMN "MEMBER"."HEIGHT" IS '키';

COMMENT ON COLUMN "MEMBER"."WEIGHT" IS '몸무게';

COMMENT ON COLUMN "MEMBER"."SESSIONKEY" IS '세션키';

COMMENT ON COLUMN "MEMBER"."SESSIONLIMIT" IS '세션시간';

COMMENT ON COLUMN "MEMBER"."GOOGLEID" IS '구글ID';

COMMENT ON COLUMN "MEMBER"."NAVERID" IS '네이버ID';

COMMENT ON COLUMN "MEMBER"."KAKAOID" IS '카카오ID';

CREATE TABLE "ADMIN" (
	"ADMIN_ID"	VARCHAR2(100)		NOT NULL,
	"ADMIN_PWD"	VARCHAR2(80)		NOT NULL,
	"ADMIN_NAME"	VARCHAR(50)		NOT NULL
);

CREATE TABLE "EXERCISE" (
	"ECODE"	NUMBER		NOT NULL,
	"EX_NAME"	VARCHAR2(20)		NOT NULL,
	"PART"	VARCHAR2(30)		NOT NULL,
	"EPOSE"	VARCHAR2(2000)		NOT NULL,
	"EPOSE_LINK"	VARCHAR2(1000)		NULL
);

COMMENT ON COLUMN "EXERCISE"."EPOSE_LINK" IS '유튜브 자세화면 보이게함';

CREATE TABLE "FOOD" (
	"FOOD_CD"	VARCHAR(20)		NOT NULL,
	"FOOD_QUANTITY"	NUMBER		NOT NULL
);

CREATE TABLE "MEMBER_EX_SET" (
	"DAY_EX_SET"	VARCHAR2(70)		NOT NULL,
	"DAY_NO"	VARCHAR2(10)		NOT NULL,
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL,
	"ECODE"	NUMBER		NOT NULL,
	"EX_NAME"	VARCHAR2(20)		NOT NULL,
	"EXERCISE_SET"	NUMBER		NOT NULL,
	"EXERCISE_NUMBER"	NUMBER		NOT NULL,
	"EXERCISE_WEIGHT"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "MEMBER_EX_SET"."DAY_EX_SET" IS '날짜,아이디,운동코드조합';

COMMENT ON COLUMN "MEMBER_EX_SET"."MEMBER_ID" IS '이메일 형식';

CREATE TABLE "FOOD_API" (
	"FOOD_CD"	VARCHAR(20)		NOT NULL,
	"FOOD_NAME"	VARCHAR(90)		NOT NULL,
	"CALORIE"	NUMBER		NULL,
	"CRABS"	NUMBER		NULL,
	"PROTEIN"	NUMBER		NULL,
	"FAT"	NUMBER		NULL
);

CREATE TABLE "DAY_DIET" (
	"DAY_DIET_CODE"	VARCHAR(20)		NOT NULL,
	"FEEDBACK"	VARCHAR(20)		NULL,
	"DAY_NO"	VARCHAR2(10)		NOT NULL,
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "DAY_DIET"."DAY_DIET_CODE" IS 'FOOD_DATE+ID';

COMMENT ON COLUMN "DAY_DIET"."MEMBER_ID" IS '이메일 형식';

CREATE TABLE "NOTICE" (
	"NOTICE_NUMBER"	NUMBER		NOT NULL,
	"ADMIN_ID"	VARCHAR2(100)		NOT NULL,
	"NOTICE_TITLE"	VARCHAR2(100)		NOT NULL,
	"NOTICE_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"NOTICE_VIEW"	NUMBER		NOT NULL,
	"NOTICE_DATE"	VARCHAR2(10)		NOT NULL
);

CREATE TABLE "USERS" (
	"USERNAME"	VARCHAR2(100)		NOT NULL,
	"PASSWORD"	VARCHAR2(80)		NOT NULL,
	"USER_ENABLED"	NUMBER	DEFAULT 1	NOT NULL,
	"AUTHORITIES"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "USERS"."USER_ENABLED" IS '기본값: 1, 나머지: 0';

CREATE TABLE "MEMBER_WEIGHT" (
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL,
	"DATE"	VARCHAR2(10)		NOT NULL,
	"WEIGHT"	NUMBER		NULL,
	"MUSCLE_MASS"	NUMBER		NULL,
	"BODY_FAT_PET"	NUMBER		NULL
);

CREATE TABLE "DIET" (
	"MEAL_CODE"	VARCHAR(20)		NOT NULL,
	"DAY_DIET_CODE"	VARCHAR(20)		NOT NULL,
	"FOOD_TIME"	VARCHAR(20)		NULL,
	"FOOD_CD"	VARCHAR(20)		NOT NULL
);

COMMENT ON COLUMN "DIET"."MEAL_CODE" IS 'DAY_DIET_KEY+FOOD_TIME';

COMMENT ON COLUMN "DIET"."DAY_DIET_CODE" IS 'FOOD_DATE+ID';

COMMENT ON COLUMN "DIET"."FOOD_TIME" IS '아침이면 A, 점심이면 B, 저녁이면 C, 아점이면 X, 점저면Y, 야식은 Z';

CREATE TABLE "CALENDAR" (
	"CALENDARNO"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(100)		NULL,
	"STARTDATE"	VARCHAR2(20)		NULL,
	"ENDDATE"	VARCHAR2(20)		NULL,
	"CONTENT"	VARCHAR2(200)		NULL,
	"DAY_NO"	VARCHAR2(10)		NOT NULL,
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "CALENDAR"."TITLE" IS '제목';

COMMENT ON COLUMN "CALENDAR"."STARTDATE" IS '시작날짜';

COMMENT ON COLUMN "CALENDAR"."ENDDATE" IS '끝나는날짜';

COMMENT ON COLUMN "CALENDAR"."CONTENT" IS '내용';

COMMENT ON COLUMN "CALENDAR"."MEMBER_ID" IS '이메일 형식';

CREATE TABLE "FOR_DAY" (
	"DAY_NO"	VARCHAR2(10)		NOT NULL,
	"MEMBER_ID"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "FOR_DAY"."MEMBER_ID" IS '이메일 형식';

CREATE TABLE "SUPLEMEN" (
	"Key"	NUMBER(2)		NOT NULL,
	"NUTRIENT"	VARCHAR(90)		NOT NULL,
	"COMMENT"	VARCHAR(4000)		NULL,
	"INTAKE"	VARCHAR(90)		NULL,
	"WORKMANSHIP"	NUMBER(2)		NOT NULL
);

COMMENT ON COLUMN "SUPLEMEN"."NUTRIENT" IS '영양소';

COMMENT ON COLUMN "SUPLEMEN"."COMMENT" IS '코멘트';

COMMENT ON COLUMN "SUPLEMEN"."INTAKE" IS '섭취방법';

COMMENT ON COLUMN "SUPLEMEN"."WORKMANSHIP" IS '숙련도';

CREATE TABLE "CHICKEN" (
	"GRADE"	VARCHAR2(2)		NOT NULL,
	"STORAGE_METHOD"	VARCHAR2(4000)		NOT NULL
);

COMMENT ON COLUMN "CHICKEN"."GRADE" IS '상품등급';

COMMENT ON COLUMN "CHICKEN"."STORAGE_METHOD" IS '보관방법';

CREATE TABLE "CHICKEN_LIST" (
	"CHICKENNO"	NUMBER(2)		NOT NULL,
	"LINK"	VARCHAR2(90)		NOT NULL,
	"PRODUCT_NAME"	VARCHAR2(20)		NOT NULL,
	"PRICE"	NUMBER(10)		NOT NULL,
	"GRADE"	VARCHAR2(2)		NOT NULL
);

COMMENT ON COLUMN "CHICKEN_LIST"."CHICKENNO" IS '닭가슴살번호';

COMMENT ON COLUMN "CHICKEN_LIST"."LINK" IS '링크';

COMMENT ON COLUMN "CHICKEN_LIST"."PRODUCT_NAME" IS '상품명';

COMMENT ON COLUMN "CHICKEN_LIST"."PRICE" IS '가격';

COMMENT ON COLUMN "CHICKEN_LIST"."GRADE" IS '상품등급';

CREATE TABLE "SUPLEMEN_LIST" (
	"NUTRIENTNO"	NUMBER(10)		NULL,
	"LINK"	VARCHAR2(90)		NULL,
	"NUTRIENTLIST"	VARCHAR(90)		NOT NULL,
	"Key"	NUMBER(2)		NOT NULL
);

COMMENT ON COLUMN "SUPLEMEN_LIST"."NUTRIENTNO" IS '보충제번호';

COMMENT ON COLUMN "SUPLEMEN_LIST"."LINK" IS '링크';

COMMENT ON COLUMN "SUPLEMEN_LIST"."NUTRIENTLIST" IS '보충제리스트';

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"COMMENT_NUM"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_ID"
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "PK_ADMIN" PRIMARY KEY (
	"ADMIN_ID"
);

ALTER TABLE "EXERCISE" ADD CONSTRAINT "PK_EXERCISE" PRIMARY KEY (
	"ECODE",
	"EX_NAME"
);

ALTER TABLE "FOOD" ADD CONSTRAINT "PK_FOOD" PRIMARY KEY (
	"FOOD_CD"
);

ALTER TABLE "MEMBER_EX_SET" ADD CONSTRAINT "PK_MEMBER_EX_SET" PRIMARY KEY (
	"DAY_EX_SET"
);

ALTER TABLE "FOOD_API" ADD CONSTRAINT "PK_FOOD_API" PRIMARY KEY (
	"FOOD_CD"
);

ALTER TABLE "DAY_DIET" ADD CONSTRAINT "PK_DAY_DIET" PRIMARY KEY (
	"DAY_DIET_CODE"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTICE_NUMBER",
	"ADMIN_ID"
);

ALTER TABLE "USERS" ADD CONSTRAINT "PK_USERS" PRIMARY KEY (
	"USERNAME"
);

ALTER TABLE "MEMBER_WEIGHT" ADD CONSTRAINT "PK_MEMBER_WEIGHT" PRIMARY KEY (
	"MEMBER_ID"
);

ALTER TABLE "DIET" ADD CONSTRAINT "PK_DIET" PRIMARY KEY (
	"MEAL_CODE"
);

ALTER TABLE "CALENDAR" ADD CONSTRAINT "PK_CALENDAR" PRIMARY KEY (
	"CALENDARNO"
);

ALTER TABLE "FOR_DAY" ADD CONSTRAINT "PK_FOR_DAY" PRIMARY KEY (
	"DAY_NO",
	"MEMBER_ID"
);

ALTER TABLE "SUPLEMEN" ADD CONSTRAINT "PK_SUPLEMEN" PRIMARY KEY (
	"Key"
);

ALTER TABLE "CHICKEN" ADD CONSTRAINT "PK_CHICKEN" PRIMARY KEY (
	"GRADE"
);

ALTER TABLE "CHICKEN_LIST" ADD CONSTRAINT "PK_CHICKEN_LIST" PRIMARY KEY (
	"CHICKENNO"
);

ALTER TABLE "SUPLEMEN_LIST" ADD CONSTRAINT "PK_SUPLEMEN_LIST" PRIMARY KEY (
	"NUTRIENTNO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_USERS_TO_MEMBER_1" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "USERS" (
	"USERNAME"
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "FK_USERS_TO_ADMIN_1" FOREIGN KEY (
	"ADMIN_ID"
)
REFERENCES "USERS" (
	"USERNAME"
);

ALTER TABLE "FOOD" ADD CONSTRAINT "FK_FOOD_API_TO_FOOD_1" FOREIGN KEY (
	"FOOD_CD"
)
REFERENCES "FOOD_API" (
	"FOOD_CD"
);

ALTER TABLE "MEMBER_EX_SET" ADD CONSTRAINT "FK_FOR_DAY_TO_MEMBER_EX_SET_1" FOREIGN KEY (
	"DAY_NO"
)
REFERENCES "FOR_DAY" (
	"DAY_NO"
);

ALTER TABLE "MEMBER_EX_SET" ADD CONSTRAINT "FK_FOR_DAY_TO_MEMBER_EX_SET_2" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "FOR_DAY" (
	"MEMBER_ID"
);

ALTER TABLE "MEMBER_EX_SET" ADD CONSTRAINT "FK_EXERCISE_TO_MEMBER_EX_SET_1" FOREIGN KEY (
	"ECODE"
)
REFERENCES "EXERCISE" (
	"ECODE"
);

ALTER TABLE "MEMBER_EX_SET" ADD CONSTRAINT "FK_EXERCISE_TO_MEMBER_EX_SET_2" FOREIGN KEY (
	"EX_NAME"
)
REFERENCES "EXERCISE" (
	"EX_NAME"
);

ALTER TABLE "DAY_DIET" ADD CONSTRAINT "FK_FOR_DAY_TO_DAY_DIET_1" FOREIGN KEY (
	"DAY_NO"
)
REFERENCES "FOR_DAY" (
	"DAY_NO"
);

ALTER TABLE "DAY_DIET" ADD CONSTRAINT "FK_FOR_DAY_TO_DAY_DIET_2" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "FOR_DAY" (
	"MEMBER_ID"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_ADMIN_TO_NOTICE_1" FOREIGN KEY (
	"ADMIN_ID"
)
REFERENCES "ADMIN" (
	"ADMIN_ID"
);

ALTER TABLE "MEMBER_WEIGHT" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_WEIGHT_1" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "DIET" ADD CONSTRAINT "FK_DAY_DIET_TO_DIET_1" FOREIGN KEY (
	"DAY_DIET_CODE"
)
REFERENCES "DAY_DIET" (
	"DAY_DIET_CODE"
);

ALTER TABLE "DIET" ADD CONSTRAINT "FK_FOOD_TO_DIET_1" FOREIGN KEY (
	"FOOD_CD"
)
REFERENCES "FOOD" (
	"FOOD_CD"
);

ALTER TABLE "CALENDAR" ADD CONSTRAINT "FK_FOR_DAY_TO_CALENDAR_1" FOREIGN KEY (
	"DAY_NO"
)
REFERENCES "FOR_DAY" (
	"DAY_NO"
);

ALTER TABLE "CALENDAR" ADD CONSTRAINT "FK_FOR_DAY_TO_CALENDAR_2" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "FOR_DAY" (
	"MEMBER_ID"
);

ALTER TABLE "FOR_DAY" ADD CONSTRAINT "FK_MEMBER_TO_FOR_DAY_1" FOREIGN KEY (
	"MEMBER_ID"
)
REFERENCES "MEMBER" (
	"MEMBER_ID"
);

ALTER TABLE "CHICKEN_LIST" ADD CONSTRAINT "FK_CHICKEN_TO_CHICKEN_LIST_1" FOREIGN KEY (
	"GRADE"
)
REFERENCES "CHICKEN" (
	"GRADE"
);

ALTER TABLE "SUPLEMEN_LIST" ADD CONSTRAINT "FK_SUPLEMEN_TO_SUPLEMEN_LIST_1" FOREIGN KEY (
	"Key"
)
REFERENCES "SUPLEMEN" (
	"Key"
);

